### ISSUE TITLE
Complete initial draft of Spatter benchmark documentation 

### ISSUE THREAD

**Issue by gshipman** [lanl/benchmarks#21]
Jered, please take a bit to work through a draft of the Spatter documentation. 
For plotting, please see the branson.rst, and associated csv and gnuplot scripts for how we are generating plots. I know these will be different for spatter but using the same mechanism would give us the same look / feel. Thx!

**Comment by JDTruj2018** [comment]
Will do. I'll work on adding weak scaling plots and any strong scaling I am able to get this evening/tomorrow when I am not locked away in a SCIF.
