### ISSUE TITLE
Rebaseline Sparta on Roci-HBM - Crossroads hardware in the open enclave 

### ISSUE THREAD

**Issue by gshipman** [lanl/benchmarks#43]
@amagela will rebaseline Sparta on Roci-HBM (same hardware as Crossroads) 
Include description of number of cores we are running on for strong scaling and why, put this in the introduction. 
Explain what we are doing, when we ramp up the number of cores, and why.. bindings, etc.. 
smallest Numa domain, 1/4, 1/2, full numa domains

Name game, Crossroads is the name. 
Crossroads

We will define crossroads in the introduction documentation.

**Comment by amagela** [comment]
I added some introduction information on Crossroads in another issue.

**Comment by amagela** [comment]
This is closed.
