### ISSUE TITLE
Rebaseline Branson on Roci-HBM 

### ISSUE THREAD

**Issue by gshipman** [lanl/benchmarks#44]
After Anthony completes rebaseline of Sparta, rebaseline using same methodology on Roci-HBM

**Comment by gshipman** [comment]
Reran Branson on SPR-DDR, awaiting access to SPR-HBM on Roci to complete. 
need to chat with Alex Long on problem sizes, 66M and up seem quite big, not in terms of memory footprint, but potentially in terms of what we would expect in a real app. Part of the issue is these particles likely carry much less data then the real up would.

**Comment by dmageeLANL** [comment]
a0ce607aea5e4dc408444b0edc89499af6298103

Has full and verified Branson results.
