### ISSUE TITLE
Rebaseline Parthenon-VIBE on Roci-HBM 

### ISSUE THREAD

**Issue by gshipman** [lanl/benchmarks#45]
After Anthony completes rebaseline of Sparta, rebaseline using same methodology on Roci-HBM

**Comment by dmageeLANL** [comment]
Complete but could use further explanation.

**Comment by gshipman** [comment]
We discussed this today, numbers look reasonable, a few changes needed: 
1) Run 20% memory size with ranks up until we run out of mesh-blocks (56 ranks) then switch to ranks + threads
2) Move ATS-3 results up top, then CTS, then A100 
3) Rerun A100 numbers

**Comment by gshipman** [comment]
done!
