### ISSUE TITLE
Rebaseline MiniEM on Roci-HBM

### ISSUE THREAD

**Issue by gshipman** [lanl/benchmarks#48]

**Comment by gshipman** [comment]
@amagela  Also need to update the problem size For SSNI here: 
https://lanl.github.io/benchmarks/00_intro/introduction.html#ssni-weights-and-ssni-problem-sizes

**Comment by gshipman** [comment]
Verification test is completed according to Trilinos folks, @amagela  will verify and run updated benchmarks and provide memory targets based on this.

**Comment by amagela** [comment]
All of this should have been addressed with changes in the April timeframe. Am closing.
