### ISSUE TITLE
Parthenon Vibe on GPUs

### ISSUE THREAD

**Issue by dmageeLANL** [lanl/benchmarks#49]
Hi Dan,
 
Just wondering do you have any update on this?
 
Thanks,
Peng
 
From: Shipman, Galen M <[gshipman@lanl.gov](mailto:gshipman@lanl.gov)> 
Sent: Friday, July 28, 2023 7:51 AM
To: Peng Wang <[penwang@nvidia.com](mailto:penwang@nvidia.com)>; Ian Karlin <[ikarlin@nvidia.com](mailto:ikarlin@nvidia.com)>
Cc: Scot Halverson <[shalverson@nvidia.com](mailto:shalverson@nvidia.com)>; Giridhar Chukkapalli <[gchukkapalli@nvidia.com](mailto:gchukkapalli@nvidia.com)>; Magee, Daniel J <[dmagee@lanl.gov](mailto:dmagee@lanl.gov)>; Paul Cook <[pacook@nvidia.com](mailto:pacook@nvidia.com)>
Subject: RE: [EXTERNAL] RE: Parthenon-VIBE Questions
 
Dan,
 
Can you check this? Try to reproduce the results on Darwin a100 first. 
 
Thanks 
 
 
Galen
 
 

From: Peng Wang <[penwang@nvidia.com](mailto:penwang@nvidia.com)>
Date: Thursday, Jul 27, 2023 at 5:00 PM
To: Shipman, Galen M <[gshipman@lanl.gov](mailto:gshipman@lanl.gov)>, Ian Karlin <[ikarlin@nvidia.com](mailto:ikarlin@nvidia.com)>
Cc: Scot Halverson <[shalverson@nvidia.com](mailto:shalverson@nvidia.com)>, Giridhar Chukkapalli <[gchukkapalli@nvidia.com](mailto:gchukkapalli@nvidia.com)>, Magee, Daniel J <[dmagee@lanl.gov](mailto:dmagee@lanl.gov)>, Paul Cook <[pacook@nvidia.com](mailto:pacook@nvidia.com)>
Subject: RE: [EXTERNAL] RE: Parthenon-VIBE Questions
 
Hi Galen, Dan,
 
Thanks for the info. The input file ([burgers.pin](https://urldefense.com/v3/__http://burgers.pin__;!!Bt8fGhp8LhKGRg!Bcq5E86qwnsTyLO3QFEqzqhazRYYq84E783H5r7I4cpY3iOMzNl8DYqKVHCzWA9_jPcqKb7DncrFtjw7$)) in the repo has meshblocks=16. However, I couldn’t reproduce the A100 performance in Table 4.4 of [https://lanl.github.io/benchmarks/3_vibe/vibe.html](https://urldefense.com/v3/__https://lanl.github.io/benchmarks/3_vibe/vibe.html__;!!Bt8fGhp8LhKGRg!Bcq5E86qwnsTyLO3QFEqzqhazRYYq84E783H5r7I4cpY3iOMzNl8DYqKVHCzWA9_jPcqKb7DnaxJSFeL$): my measured A100 perf is ~ 4X lower than Table 4.4 with meshblocks=16. However, if I use meshblocks=32, I would get numbers much closer to Table 4.4.
 
So I want to double check did you use meshblocks=16 or 32 for the result in Table 4.4?
 
Thanks,
Peng
 
From: Shipman, Galen M <[gshipman@lanl.gov](mailto:gshipman@lanl.gov)> 
Sent: Thursday, July 27, 2023 4:27 PM
To: Ian Karlin <[ikarlin@nvidia.com](mailto:ikarlin@nvidia.com)>
Cc: Scot Halverson <[shalverson@nvidia.com](mailto:shalverson@nvidia.com)>; Giridhar Chukkapalli <[gchukkapalli@nvidia.com](mailto:gchukkapalli@nvidia.com)>; Magee, Daniel J <[dmagee@lanl.gov](mailto:dmagee@lanl.gov)>; Paul Cook <[pacook@nvidia.com](mailto:pacook@nvidia.com)>; Peng Wang <[penwang@nvidia.com](mailto:penwang@nvidia.com)>
Subject: Re: [EXTERNAL] RE: Parthenon-VIBE Questions
 
Ian, (Looping in Dan Magee)
 
For Parthenon-VIBE only the parthenon/mesh/nx* parameters may be changed (to adjust memory footprint).
We would like to see 20%/40%/60% memory footprint results.
 
Thanks!

Galen
 
 
 
 
 
 
From: Ian Karlin <[ikarlin@nvidia.com](mailto:ikarlin@nvidia.com)> 
Sent: Wednesday, July 12, 2023 2:57 PM
To: Shipman, Galen M (EXTERNAL) <[gshipman@lanl.gov](mailto:gshipman@lanl.gov)>
Cc: Giridhar Chukkapalli <[gchukkapalli@nvidia.com](mailto:gchukkapalli@nvidia.com)>; Scot Halverson <[shalverson@nvidia.com](mailto:shalverson@nvidia.com)>; Paul Cook <[pacook@nvidia.com](mailto:pacook@nvidia.com)>; Peng Wang <[penwang@nvidia.com](mailto:penwang@nvidia.com)>
Subject: Parthenon-VIBE Questions
 
Hi Galen,
 
A couple of questions about Parthenon-VIBE that would help us with our initial modeling of this.
 
Can you please document the settings used in your runs so we can recreate the results and understand the baseline?
 
Then, can you document the settings for the benchmark problem that can be changed and those that can’t be changed from the baseline runs.  In particular, meshblocks, numlevels, nlim and tlim?
 
Thanks and let us know if you have any questions,
 
Ian

**Comment by bvillasen** [comment]
I also report that I observe inconsistent A100 performance compared to the reported figure of merit (zone-cycles/wallsecond), as communicated previously.

On an 80 GB A100, I measure 3-4x slower performance than reported for mesh sizes of 32^3 and 64^3. While for mesh sizes of 96^3 and 128^3, I measure performance that is 6-7x slower.
For mesh sizes of 160^3 and 192^3, the run fails with the following error message:
```
### PARTHENON ERROR
  Message:     Number of tags exceeds the maximum allowed by the MPI standard.
  File:        /home/bvillasen/code/ATS5_Parthenon/benchmarks/parthenon/src/bvals/comms/tag_map.cpp
  Line number: 54
```

On a 40 GB A100, mesh sizes of 128^3 and higher fail due to insufficient memory, with error message:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos failed to allocate memory for label "Ulz".  Allocation using MemorySpace named "Cuda" failed with the following error:  Allocation of size 1.16 M failed, likely due to insufficient memory.  (The allocation mechanism was cudaMalloc().  The Cuda allocation returned the error code ""cudaErrorMemoryAllocation".)
```

All runs use the  parameters specified in the [benchmark description](https://lanl.github.io/benchmarks/03_vibe/vibe.html):
```
NXB=16
NLIM=250
NLVL=3
```
And executed as follows:
```
burgers-benchmark -i burgers.pin  parthenon/mesh/nx1=${NX} parthenon/mesh/nx2=${NX} parthenon/mesh/nx3=${NX} parthenon/meshblock/nx1=${NXB} parthenon/meshblock/nx2=${NXB} parthenon/meshblock/nx3=${NXB} parthenon/time/nlim=${NLIM} parthenon/mesh/numlevel=${NLVL}
```

Please confirm the parameters that should be used to measure the reference performance.

**Comment by gshipman** [comment]
@bvillasen  We are cleaning up older issues as we prepare for a final version of the benchmarks, can you confirm is the perf variability issue described above still an issue for you? Thanks, Galen

**Comment by gshipman** [comment]
I believe this issue is resolved. Closing, please ping if still an issue.
