### ISSUE TITLE
Update Branson docs here to indicate no need for Metis (and how to disable it if necessary) 

### ISSUE THREAD

**Issue by gshipman** [lanl/benchmarks#50]
@alexrlongne will be updating Branson Readme to indicate no need for Metis in certain cases, we should document this here as well.

**Comment by alexrlongne** [comment]
Documentation is now up to date regarding OpenMP and Metis in the develop branch of Branson at https://github.com/lanl/branson/

**Comment by gshipman** [comment]
Done!

**Comment by gshipman** [comment]
@gshipman needs to check this is in the docs on benchmark site.

**Comment by gshipman** [comment]
Closed! Docs updated to reflect single node without Metis, multi with Metis.
