### ISSUE TITLE
Stream benchmark 

### ISSUE THREAD

**Issue by gshipman** [lanl/benchmarks#54]
1) Update table to indicate MB/sec for bandwidth 
2) Make second column BW/core 
3) Add third column - Total BW (core * BW/core) 
4) Modify plot - y axis should indicate BW/core  or BW/processing element 
5) Add new plot that has total BW on y axis 
6) remove cray/rhel stuff,, other sections that aren't used.. etc.. 
7) Add data for SPR HBM (from Roci)

**Comment by dmageeLANL** [comment]
1, 2, 3, 4, 5, 6 in 6b066dd

**Comment by dmageeLANL** [comment]
Done
